# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Sauron' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 4.7'
    pod 'TransitionButton'
#    pod 'SwiftyCam', :git => 'https://github.com/Awalz/SwiftyCam.git', :branch => 'Swift4'
    pod 'PopupDialog', '~> 0.9'

end
